<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
$posts = $this->getPosts(); ?>

<div class="container">

<?php if( $this->getCategory()->getTitle() == "Press" ){ ?>

  <header class="page-header">
    <h1 class="page-title">Press Mentions</h1>
  </header>

<?php } else { ?>

  <header class="page-header">
    <h1 class="page-title"><?php echo $this->getCategory()->getTitle(); ?></h1>
  </header>

<?php } ?>

</div>

<div class="wrapper blog-list">
  <div class="container">

  <?php if (count($posts)): ?>

    <ul class="posts magazine-posts">

      <?php foreach ($posts as $post): ?>

        <?php if( $this->getCategory()->getTitle() === "Press" ){ ?>

          <li class="post ">

            <div class="post-img"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post->getFeaturedImage() ?>" alt="" /></div>
            <header class="post-header">
              <h1 class="post-title"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h1>
            </header>

            <time><?php echo $post->getCreatedTime(); ?></time>

            <div class="postContent">
              <?php echo $post->getPostContent(); ?>
            </div>

            <div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
            <div class="postDetails">
                <?php if ($this->getCommentsEnabled()): ?>
                    <?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo Mage::helper('blog')->__('Comments'); ?></a> |
                <?php endif; ?>
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                    <?php echo Mage::helper('blog')->__('Posted in'); ?>
                    <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php echo Mage::helper('blog')->__('Posted'); ?>
                <?php endif; ?><?php echo$this->__("By"); ?> <?php echo $post->getUser(); ?></div>
          </li>

        <?php } else { ?>

          <li class="post magazine-post">
          <article>
            <div class="post-img"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$post->getFeaturedImage() ?>" alt="" /></div>
            <div class="content">
              <header class="header">
                <div class="meta">
                    <div class="categories">
                      <?php if ( !empty( $postCats ) ): $i = 0;
                          foreach ( $postCats as $data ): ?>
                            <a href="<?php echo $data['url']; ?>"><?php $i == 0 ? print $data['title'] : print ', '.$data['title'] ;  ?></a>
                          <?php $i++; endforeach;
                      endif; ?>
                    </div>
                  </div>
                <h1 class="title"><a href="<?php echo $post->getAddress(); ?>"><?php echo $post->getTitle(); ?></a></h1>
              </header>
              <div class="short-desc white">
                <p><?php echo $post->getShortContent()  ?></p>
                <span></span>
              </div>
              <footer>
                <time>
                  <?php echo $post->getCreatedTime(); ?>
                </time>
              </footer>
            </div>
          </article>
        </li>

        <?php } ?>

      <?php endforeach; ?>

    </ul>

  <?php else: ?>

    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>

  <?php endif; ?>

  </div>
</div>

<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>