<?php
/**
 * @category    Inchoo
 * @package     Inchoo Featured Products
 * @author      Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */

$image_size = (int) Mage::getStoreConfig("featuredproducts/cmspage/max_image_dimension");
$_products = $this->getProductCollection();

if ( $_products->getSize() > 0 ): ?>

<div data-featured-product-list="true">

<?php foreach ( $_products->getItems() as $_product ): ?>

    <li class="featured-product">
      <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
        <img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
      </a>
      <h2 class="product-name">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
          <?php echo $this->htmlEscape($_product->getName()) ?>
        </a>
      </h2>
      <?php echo $this->getPriceHtml($_product, true, '-new') ?>
    </li>

  <?php endforeach; ?>

</div>

<?php endif; ?>