<?php
include_once "app/Mage.php";
umask(0);
Mage::app()->loadArea('frontend');

$coupon_code = '';

$model     = Mage::getModel('salesrule/rule');
$generator = Mage::getModel('salesrule/coupon_massgenerator');
$model->load(12);

$generator->setDash(4);
$generator->setLength(12);
$generator->setPrefix('NEWS-');

$model->setCouponCodeGenerator($generator);
$model->setCouponType( $model::COUPON_TYPE_AUTO );

$coupon = $model->acquireCoupon();
$coupon->setType( Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED )->save();

$coupon_code = $coupon->getCode();

require_once ( 'lib/Mailchimp/mailchimp.php');

$data = $_POST;

if( $data['mchmp_email'] != null )
{
  $mchmp = new Mailchimp( Mage::getStoreConfig('monkey/general/apikey') );

  $args = array(
    'id'                => Mage::getStoreConfig('monkey/general/newsletter_signup_list'),
    'email'             => array( 'email' => $data['mchmp_email'] ),
    'merge_vars'        => array('DSCNT1' => $coupon_code ),
    'email_type'        => 'html',
    'double_optin'      => true,
    'update_existing'   => true,
    'replace_interests' => true,
    'send_welcome'      => true,
  );

  $result = json_encode( $mchmp->call('lists/subscribe', $args ) );

  echo $result;
}
