
<div class="container">
  <header class="page-header">
    <h1 class="page-title"><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
  </header>
</div>

<div class="wrapper contact-columns">
  <ul class="container">
    <li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-email-column')->toHtml();?></li>
    <li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-address-column')->toHtml();?></li>
    <li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-phone-column')->toHtml();?></li>
  </ul>
</div>

