<ul class="featured-product-list inline">
  <li class="product">
    <img src="<?php echo $this->getSkinUrl('images/featured-chair.jpg');?>" alt="" />
  </li>
  <li class="product">
    <img src="<?php echo $this->getSkinUrl('images/featured-chair-2.jpg');?>" alt="" />
  </li>
  <li class="product">
    <img src="<?php echo $this->getSkinUrl('images/featured-chair.jpg');?>" alt="" />
  </li>
  <li class="product">
    <img src="<?php echo $this->getSkinUrl('images/featured-chair-3.jpg');?>" alt="" />
  </li>
</ul>
