<?php $media = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>
<div class="wrapper horizontal-sliders" id="js-clients">


  <div class="wrapper table horizontal-slider">

    <div class="table-cell horiz-slider-content" style="background-color:#c68d00">
      <h4>Hospitality</h4>
      <h3>MARRIOTT FLAGSHIP PORTLAND OREGON</h3>
      <p>Marriott approached Industry West to manufacture customized seating for a new flagship hotel in Downtown Portland Oregon. Marriott required a custom matched Pantone color and and seat cushion for 700 Bar stools for it individual Rooms. Working with a team of architects and interior designers we were able to meet all delivery timelines to ensure the seating was ready for their successful launch of this property.</p>
    </div>

    <div class="table-cell horiz-slider-images">
      <ul class="js-slider" data-client-slider="true" data-slider-id="slider-1">
        <li><img src="<?php echo $media ?>images/marriott/slide_1.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/marriott/slide_2.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/marriott/slide_3.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/marriott/slide_4.jpg" alt="" /></li>
      </ul>
    </div>

  </div>


  <div class="wrapper table horizontal-slider">

    <div class="table-cell horiz-slider-content" style="background-color:#3c8bcc">
      <h4>RESTAURANT</h4>
      <h3>MELLOW MUSHROOM WRIGHTSVILLE BEACH</h3>
      <p>What's better than pizza at the beach? Mellow Mushroom Wrightsville Beach requested some easy breezy stools and chairs to give the casual restaurant a laid-back vibe. Our Marais style fit their aesthetic perfectly, and we were able to meet their schedule and requested quantity on time. </p>
    </div>

    <div class="table-cell horiz-slider-images">
      <ul class="js-slider" data-client-slider="true" data-slider-id="slider-2">
        <li><img src="<?php echo $media ?>images/mellow/slide_1.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_2.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_3.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_4.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_5.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_6.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_7.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_8.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_9.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mellow/slide_10.jpg" alt="" /></li>
      </ul>
    </div>

  </div>


  <div class="wrapper table horizontal-slider">

    <div class="table-cell horiz-slider-content" style="background-color:#cd174e">
      <h4>RESTAURANT</h4>
      <h3>Project Pie</h3>
      <p>Our Freshman Chairs and Montclair Bar Stools hit the spot at this tasty pizza destination. Featuring artisan build-your-own pies, Project Pie started out as a simple quest for custom pizza at a fair price, and quickly grew to an international franchise with 15 locations (and growing!). </p>
      <small>All photo credit to Jonathan Zizzo</small>
    </div>

    <div class="table-cell horiz-slider-images">
      <ul class="js-slider" data-client-slider="true" data-slider-id="slider-2">
        <li><img src="<?php echo $media ?>images/projectpie/slide_1.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/projectpie/slide_2.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/projectpie/slide_3.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/projectpie/slide_4.jpg" alt="" /></li>
      </ul>
    </div>

  </div>


  <div class="wrapper table horizontal-slider">

    <div class="table-cell horiz-slider-content" style="background-color:#e97539">
      <h4>RESTAURANT</h4>
      <h3>M Shack</h3>
      <p>We were more than happy to oblige when MShack restaurant, a local favorite here in Jacksonville, ordered chairs for their hometown location. Tasty old fashioned burgers just taste better when you're sitting in a solid seat. </p>
    </div>

    <div class="table-cell horiz-slider-images">
      <ul class="js-slider" data-client-slider="true" data-slider-id="slider-2">
        <li><img src="<?php echo $media ?>images/mshack/slide_1.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_2.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_3.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_4.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_5.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_6.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_7.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_8.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_9.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_10.jpg" alt="" /></li>
        <li><img src="<?php echo $media ?>images/mshack/slide_11.jpg" alt="" /></li>
      </ul>
    </div>

  </div>


</div>
