<?php

$scroll = $this->getData('scroll_to_anchor');
$offset = $this->getData('scroll_offset') ?>

<?php if( $scroll != null ){ ?>

<div class="wrapper scroll-to-anchor">
  <div class="scroll-anchor-link">
    <a href="#" class="btn" data-scroll-to="true" data-scroll-to-anchor="<?php echo $scroll; ?>" data-scroll-offset="<?php echo $offset;?>"><i class="fa fa-chevron-down"></i></a>
  </div>
</div>

<?php } ?>