
<div class="wrapper timeline" id="js-timeline">
  <div class="container" data-timeline-container="true">

    <div class="wrapper table timeline-block ltr" data-timeline-block="true">
      <div class="table-cell timeline-block-intro right">
        <h2>Inspiration can hit at any place, at any time.</h2>
        <img src="<?php echo $this->getSkinUrl('images/process-1.jpg'); ?>" alt="" />
      </div>
      <div class="table-cell timeline-block-content" data-push-content="true">
        <p>We strive to keep our focus on clean and modern designs: a nod to the past while defining the style of the future. Blending the finest materials with timeless and contemporary silhouettes allows us to create dynamic pieces for any environment. Vintage items are often placed into production after years of obsolescence and reintroduced with modern colors and finishes.</p>
      </div>
    </div>


    <div class="wrapper table timeline-block rtl" data-timeline-block="true">
      <div class="table-cell timeline-block-intro ">
        <h2>We collaborate with our manufacturer to create a prototype</h2>
        <img src="<?php echo $this->getSkinUrl('images/process-2.jpg'); ?>" alt="" />
      </div>

      <div class="table-cell timeline-block-content" data-push-content="true">
        <p>Long frustrated with a desire to acquire furniture and home goods that were far out of reach, we exist to defy the idea that the only option left to the consumer is mass produced, cheap, and uninspired. Working with select factories in the USA, Southern China, Vietnam, Indonesia and Europe, we prepare the necessary tooling, molds and materials necessary for production.</p>
      </div>
    </div>


    <div class="wrapper table timeline-block ltr" data-timeline-block="true">
      <div class="table-cell timeline-block-intro right">
        <h2>Using only the most durable steel, we build the strongest chair on the market</h2>
        <img src="<?php echo $this->getSkinUrl('images/process-3.jpg'); ?>" alt="" />
      </div>
      <div class="table-cell timeline-block-content" data-push-content="true">
        <p>Our products are built to last. We use only the strongest materials so that you can rest easy, safe in the knowledge that you are on solid seating. By capitalizing on genuine relationships with our factories and their owners, we are able to ensure the reliability and quality of each item that we send to you.</p>
      </div>
    </div>


    <div class="wrapper table timeline-block rtl" data-timeline-block="true">
      <div class="table-cell timeline-block-intro ">
        <h2>the finished product is shipped to one of our warehouses, where we apply the necessary finishes</h2>
        <img src="<?php echo $this->getSkinUrl('images/process-4.jpg'); ?>" alt="" />
      </div>
      <div class="table-cell timeline-block-content" data-push-content="true">
        <p>With distribution on the West and East coasts, lead times are cut in half. While many companies advertise a product for sale without even owning or stocking it, we stock tens of thousands of pieces with thousands more arriving every week.</p>
      </div>
    </div>


    <div class="wrapper table timeline-block ltr" data-timeline-block="true">
      <div class="table-cell timeline-block-intro right">
        <h2>Signed, sealed, delivered! time to make it your own.</h2>
        <img src="<?php echo $this->getSkinUrl('images/process-5.jpg'); ?>" alt="" />
      </div>
      <div class="table-cell timeline-block-content" data-push-content="true">
        <p>If you are not 100% satisfied, we will do whatever it takes to make you happy. We guarantee every product the we deliver and stand by our industry leading warranty.</p>
      </div>
    </div>

  </div>
</div>