<?php

$formErrors = $this->getParentBlock()->formErrors;
$formErrors = (!empty($formErrors['billing_errors'])) ? $formErrors['billing_errors'] : array();

$helper = Mage::helper('onestepcheckout/checkout');
$dataHelper = Mage::helper('onestepcheckout');


  // FIRST NAME
  $billingFields['firstname'] = '<li class="half input-firstname'.((in_array('firstname', $formErrors)) ? ' input-error' : '').'">
                                   <label for="billing:firstname">'.$this->__('First Name').'<span class="required">*</span></label>
                                   <input class="required-entry input-text" type="text" name="billing[firstname]" id="billing:firstname" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getFirstname()).'" />
                                 </li>';


  // LAST NAME
  $billingFields['lastname'] = '<li class="half right input-lastname'.((in_array('lastname', $formErrors)) ? ' input-error' : '').'">
                                  <label for="billing:lastname">'.$this->__('Last Name').' <span class="required">*</span></label>
                                  <input class="required-entry input-text" type="text" name="billing[lastname]" id="billing:lastname" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getLastname()).'" />
                                </li>';


  // EMAIL ALREADY REGISTERED
  if( !$this->isCustomerLoggedIn() || in_array('email_registered', $formErrors) ):

    $billingFields['email'] = '<li class="full clear" id="onestepcheckout-email-error" '.((!in_array('email_registered', $formErrors)) ? 'style="display: none"' : '').'>
                                    <div id="onestepcheckout-email-error-message" data-checkout-alert="true" class="error-msg">'.
                                        ((in_array('email_registered', $formErrors)) ? $this->__('<p>Email address already registered. Please <a href="#" data-login-link="login">login now</a> or use a different email address.</p>') : $this->__('Invalid email address.'))
                                    .'</div>
                               </li>';
  endif;


  // REGULAR EMAIL
  if( !$this->isCustomerLoggedIn() ):

    $billingFields['email'] = $billingFields['email'].'<li class="half input-box input-email'.((in_array('email', $formErrors)) ? ' input-error' : '').'">
                                                        <label for="billing:email">'.$this->__('Email Address').' <span class="required">*</span>&nbsp;&nbsp;<i class="fa fa-spinner fa-spin" data-email-checking="true" style="display:none;"></i></label>
                                                        <input type="text" name="billing[email]" id="billing:email" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getEmail()).'" class="validate-email required-entry input-text" />
                                                      </li>';
  endif;




  // PHONE
  if(!$this->settings['exclude_telephone']):

    $billingFields['telephone'] = '<li class="half right">
                                      <div class="half input-box input-telephone'.((in_array('telephone', $formErrors)) ? ' input-error' : '').'">
                                          <label for="billing:telephone">'.$this->__('Telephone').' <span class="required">*</span></label>
                                          <input type="text" name="billing[telephone]" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getTelephone()).'" class="required-entry input-text" id="billing:telephone" />
                                      </div>
                                   </li>';

  endif;



  // ADDRESS FIELDS
  if(!$this->settings['exclude_address']):

    $exclude = Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_address_fields');
    $addressFields = '';

    if( $exclude ):

      for ( $_i = 1, $_n = $this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++)
      {
        $addressFields .= '<li class="full input-box input-address-short'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                            <label for="billing:street'.$_i.'">'.$this->__('Street Address '.$_i).'<span class="required">*</span></label>
                            <input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet($_i)).'" class="required-entry input-text onestepcheckout-address-line" />
                          </li>';
      }

      $billingFields['street'] = $addressFields;

    else:


      for ($_i=1, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++)
      {

        $addressFields .= '<input type="text" title="'.$this->__('Street Address '.$_i).'" name="billing[street][]" id="billing:street'.$_i.'" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getStreet($_i)).'" class="'.(($_i == 1)? 'required-entry ' : '').'input-text onestepcheckout-address-line" />';

        $addressFields .= (($_i != $this->helper('customer/address')->getStreetLines()) ? '': '');
      }

      $billingFields['street'] = '<li class="full"><div class="input-box input-address'.((in_array('address', $formErrors)) ? ' input-error' : '').'">
                                      <label for="billing:street1">'.$this->__('Address').'<span class="required">*</span></label>
                                      '.$addressFields.'
                                  </div></li>';

    endif;

  endif;




  if(!$this->settings['exclude_country_id']):

  $billingFields['country_id'] = '<li class="half ">
      <div class="input-box input-country'.((in_array('country', $formErrors)) ? ' input-error' : '').'">
          <label for="billing:country_id">'.$this->__('Country').' <span class="required">*</span></label>
              '.$this->getCountryHtmlSelect('billing').'
      </div></li>';

  else:

    $billingFields['country_id'] = ' <input type="hidden" name="billing[country_id]" id="billing:country_id" value="'.$this->settings['default_country'].'" />';

  endif;



  if(!$this->settings['exclude_region']):

    $billingFields['region_id'] = '<li class="half">
          <div class="input-box input-region'.((in_array('region', $formErrors)) ? ' input-error' : '').'">
              <label for="billing:region">'.$this->__('State/Province').' <span class="required">*</span></label>
              <select id="billing:region_id" name="billing[region_id]" title="'.$this->__('State/Province').'" class="validate-select" style="display:none">
                  <option value="">'.$this->__('-- Please select --').'</option>
              </select>
              <script type="text/javascript">
                  $("billing:region_id").setAttribute("defaultValue",  "'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getRegionId()).'");
              </script>
              <input type="text" id="billing:region" name="billing[region]" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getRegion()).'"  title="'.$this->__('State/Province').'" class="required-entry input-text" style="display:none" />
          </div></li>';

  endif;



  if(!$this->settings['exclude_city']):

    $billingFields['city'] = '<li class="half right ">
          <div class="input-box input-city'.((in_array('city', $formErrors)) ? ' input-error' : '').'">
              <label for="billing:city">'.$this->__('City').' <span class="required">*</span></label>
              <input type="text" name="billing[city]" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getCity()).'" title="'.$this->__('City').'" class="required-entry input-text" id="billing:city" />
          </div></li>';

  endif;




  if(!$this->settings['exclude_zip']):

    $billingFields['postcode'] = '<li class="half right zip">
          <div class="input-box input-postcode'.((in_array('postcode', $formErrors)) ? ' input-error' : '').'" >
              <label for="billing:postcode">'.$this->__('Zip/Postal Code').' <span class="required">*</span></label>
              <input type="text" title="'.$this->__('Zip/Postal Code').'" name="billing[postcode]" id="billing:postcode" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getPostcode()).'" class="validate-zip-international required-entry input-text" />
          </div></li>';
  endif;




  if(!$this->settings['exclude_company']):

    $billingFields['company'] = '<li class="half ">
                                  <div class="input-box input-company'.((in_array('company', $formErrors)) ? ' input-error' : '').'">
                                      <label for="billing:company">'.$this->__('Company').'</label>
                                      <input type="text" name="billing[company]" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getCompany()).'" title="'.$this->__('Company').'" class="input-text" id="billing:company" />
                                  </div>
                                </li>';

  endif;




  if(!$this->settings['exclude_fax']):

    $this->isCustomerLoggedIn() ? $class = '' : $class = 'right' ;

    $billingFields['fax'] = '<li class="half '.$class.'">
                              <div class="input-box input-fax'.((in_array('fax', $formErrors)) ? ' input-error' : '').'">
                                  <label for="billing:fax">'.$this->__('Fax').'</label>
                                  <input type="text" name="billing[fax]" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getFax()).'" title="'.$this->__('Fax').'" class="input-text" id="billing:fax" />
                              </div>
                            </li>';


  endif;



  $_taxvat = false;

  try
  {
    if(Mage::getStoreConfig('onestepcheckout/exclude_fields/enable_pillwaxeuvat_support'))
    {
        $_taxvat = $this->getLayout()->createBlock('euvat/widget_taxvat');
    }
  }
  catch (Exception $e)
  {

  }

  if(!is_object($_taxvat))
  {
    $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
  }



  if(is_object($_taxvat) && $_taxvat->isEnabled()):

    $billingFields['taxvat'] =
              $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                  ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
  endif;



  if (method_exists(Mage::helper('customer/address'), 'isVatAttributeVisible') && Mage::helper('customer/address')->isVatAttributeVisible()) :

    $billingFields['taxvat'] = '<li class="wide">
                                    <label for="billing:vat_id">'.$this->__('VAT Number').'</label>
                                    <input type="text" id="billing:vat_id" name="billing[vat_id]" value="'.$dataHelper->clearDash($this->getQuote()->getBillingAddress()->getVatId()).'" class="input-text '.Mage::helper('customer/address')->getAttributeValidationClass('vat_id').'" />
                                </li>';

  endif;



  try
  {
    $_dob = $this->getLayout()->createBlock('customer/widget_dob');
  }
  catch (Exception $e)
  {
    $_dob = false;
  }


  try
  {
    $_gender = $this->getLayout()->createBlock('customer/widget_gender');
  }
  catch (Exception $e)
  {
    $_gender = false;
  }


  if ( is_object($_dob) && $_dob->isEnabled()):

    $billingFields['dob'] = '<li>
        <div class="field">
            '.$_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div></li>';
  endif;


  if ( is_object($_gender) && $_gender->isEnabled()):

    $billingFields['gender'] = '<li>
        <div class="field">
            '.$_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml().'
        </div></li>';

  endif;



  if(!$this->isCustomerLoggedIn() && $helper->showCreateAccount()):


  $billingFields['create_account'] = '
        <li class="checkbox">
            <input id="id_create_account" type="checkbox" name="create_account" value="1" '.((isset($_POST['create_account']) && $_POST['create_account'] == '1') ? ' checked="checked"' : '').' />
            <label for="id_create_account">'.$this->__('Create an account for later use').'</label>

            <script>
              document.observe("dom:loaded", function()
              {
                $("id_create_account").observe("click", function(e)
                {
                  var element = e.element();
                  if(element.checked)
                  {
                    $("onestepcheckout-li-password").show();
                  }
                  else
                  {
                    $("onestepcheckout-li-password").hide();
                  }
                });
              });
            </script>
        </li>';

  endif;





  if( $helper->showPasswords() && !$this->isCustomerLoggedIn() ):

    $billingFields['password'] = ' <li class="full" id="onestepcheckout-li-password" '.(($helper->hidePasswords()) ? 'style="display: none;"':'').'>
                                    <div class="input-box input-password'.((in_array('password', $formErrors)) ? ' input-error' : '').'">
                                      <label for="billing:customer_password">'.$this->__('Password').'</label>
                                      <input type="password" class="input-text required-entry validate-password" value="" title="Password" id="billing:customer_password" name="billing[customer_password]"/>
                                    </div>
                                    <br />
                                    <div class="input-box input-password'.((in_array('confirm_password', $formErrors)) ? ' input-error' : '').'">
                                      <label for="billing:confirm_password">'.$this->__('Confirm password').'</label>
                                      <input type="password" class="input-text required-entry validate-cpassword" value="" id="billing:confirm_password" title="Confirm Password" name="billing[confirm_password]"/>
                                    </div>
                                  </li>';

  endif;






  if( $this->isCustomerLoggedIn() && $this->customerHasAddresses() ):

    $save = $dataHelper->clearDash( $this->getQuote()->getBillingAddress()->getSaveInAddressBook() );

    //$billingFields['save_in_address_book'] = '<li class="control checkbox">
    //                                            <input type="checkbox" name="billing[save_in_address_book]" value="1" id="billing:save_in_address_book" onchange="shipping.setSameAsBilling(false);" '.($save ? 'checked="checked"':'').' class="checkbox" />
    //                                            <label for="billing:save_in_address_book">'.$this->__('Save in address book').'</label>
    //                                          </li>';


  else:

    // ALWAYS SAVE ANY BILLING ADDRESS TO ADDRESS BOOK.
    $billingFields['save_in_address_book'] = '<li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>';

  endif;






  $billingFields = $this->getBillingFieldsOrder($billingFields);



foreach($billingFields as $key => $value):

  if( !empty( $value['has_li'] ) ):
    echo implode('', $value['fields']);
  else:
    echo implode('', $value['fields'] );
  endif;

endforeach;
