<?php

$step_counter = 1;
$helper = Mage::helper('onestepcheckout/checkout'); ?>

<!-- GLOBAL CHECKOUT PAGE INFORMATION START-->

<header class="page-header">
  <h1 class="page-title">Checkout</h1>
</header>

<div class="wrapper checkout">

<?php if(isset($this->formErrors['unknown_source_error'])): ?>
  <ul class="messages">
    <li class="error-msg">
      <?php echo $this->formErrors['unknown_source_error']; ?>
    </li>
  </ul>
<?php endif; ?>

<?php if($this->settings['checkout_description']): ?>
  <p class="onestepcheckout-description"><?php echo $this->settings['checkout_description']; ?></p>
<?php endif; ?>

<?php if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
  <p class="onestepcheckout-login-link">
    <a data-popup-link="login" href="#"><?php echo $this->__('Already registered? Click here to login.'); ?></a>
  </p>
<?php endif; ?>

<!-- GLOBAL CHECKOUT PAGE INFORMATION END -->


<!-- GLOBAL CHECKOUT PAGE FORM START-->

<?php if(!$this->canCheckout() || !$this->validateMinimumAmount()): ?>

  <?php if($this->canCheckout() && !$this->validateMinimumAmount()): ?>
    <p><?php echo Mage::getStoreConfig('sales/minimum_order/description'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
  <?php else: ?>
    <p><?php echo $this->__('You need to have products in your cart to checkout, and your cart is empty.'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
  <?php endif; ?>

<?php else: ?>

  <form id="onestepcheckout-form" class=" onestepcheckout" method="post" action="<?php echo $this->getUrl('onestepcheckout', array('_secure'=>true )); ?>">



    <!-- BILLING & SHIPPING & PAYMENT -->
    <div class="wrapper table onestepcheckout">

      <div class="table-cell half billing">

        <header class="checkout-step">
          <span class="checkout-step-number"><?php echo $step_counter; ?></span>
          <h2><?php echo $this->__('Billing & Shipping Addresses'); ?></h2>
        </header>

        <div id="billing_address" class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">

            <?php if(isset($this->formErrors['billing_error']) && count($this->formErrors['billing_errors']) > 0): ?>
              <div data-checkout-alert="true" class="error-msg">
                <p><?php echo $this->__('Please check red fields below and try again.'); ?></p>
              </div>
            <?php endif; ?>

            <div id="billing_address">
              <script type="text/javascript"> var billing = new Billing(); </script>
              <ul>

                  <?php if ($this->customerHasAddresses()): ?>
                    <li class="full">
                      <label for="billing-address-select"><?php echo $this->__('Select a billing address:') ?></label>
                      <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </li>
                  <?php endif; ?>

                  <ul id="billing_address_list" <?php echo (($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('billing')) ? 'style = "display:none"' : false ); ?>>
                    <?php echo $this->getChildHtml('billing_address');?>
                    <?php $addressAttributes = $this->getChild('customer_form_billing_address_user_defined_attributes');?>
                    <?php if ($addressAttributes): ?>
                      <?php $addressAttributes->setEntity($this->getQuote()->getBillingAddress())->setEntityType('customer_address');?>
                      <?php $addressAttributes->setFieldIdFormat('billing:%1$s')->setFieldNameFormat('billing[%1$s]');?>
                      <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                    <?php endif;?>
                    <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
                    <?php if ($customerAttributes): ?>
                      <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat('billing:%1$s');?>
                      <?php $customerAttributes->setFieldNameFormat('billing[%1$s]')->setShowContainer(false);?>
                      <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
                    <?php endif;?>
                  </ul>

                  <li class="checkbox">
                    <?php $uncheck = (!empty($_POST['billing']) && empty($_POST['billing']['use_for_shipping']));?>
                    <?php if($this->differentShippingAvailable()): ?>
                      <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" <?php echo (($this->sameAsBilling() && !$uncheck) ? 'checked="checked" ':'')?>/>
                      <label for="billing:use_for_shipping_yes"><?php echo $this->__('Ship to the same address')?></label>
                    <?php else: ?>
                      <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" />
                    <?php endif; ?>
                  </li>

                </ul>
            </div>

        </div>

        <div id="shipping_address" class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>" <?php echo (($this->sameAsBilling() && !$uncheck) ? 'style="display: none"': false );?>>

        <?php // SHIPPING ADDRESS ?>
        <?php if($this->differentShippingAvailable()): ?>
          <div class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">
            <script type="text/javascript"> var shipping = new Shipping(); </script>

            <?php if ($this->customerHasAddresses()): ?>
             <li class="full">
                <label for="shipping-address-select"><?php echo $this->__('Select a shipping address:') ?></label>
                <div class="input-box"><?php echo $this->getAddressesHtmlSelect('shipping') ?></div>
             </li>
            <?php endif ?>

            <ul id="shipping_address_list" <?php if($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('shipping')) { echo '  style="display: none;" '; } ?>>
              <?php echo $this->getChildHtml('shipping_address');?>
              <?php $addressAttributes = $this->getChild('customer_form_shipping_address_user_defined_attributes');?>
              <?php if ($addressAttributes): ?>
                  <?php $addressAttributes->setEntity($this->getQuote()->getShippingAddress())->setEntityType('customer_address');?>
                  <?php $addressAttributes->setFieldIdFormat('shipping:%1$s')->setFieldNameFormat('shipping[%1$s]');?>
                  <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
              <?php endif;?>
              <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getQuote()->getShippingAddress()->getId() ?>" id="shipping:address_id" />
            </ul>
          </div>
        <?php endif; ?>

        </div>

      </div>

      <div class="table-cell half payment">

        <?php $step_counter++ ?>

        <header class="checkout-step">
          <span class="checkout-step-number"><?php echo $step_counter; ?></span>
          <h2><?php echo $this->__('Promo Codes'); ?></h2>
        </header>

        <div class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">

            <!-- COUPON DISCOUNTS -->
            <?php if($this->settings['enable_discount']): $_couponcode = $this->getQuote()->getCouponCode();  ?>
              <div class="checkbox">
                <input type="checkbox" value="0" data-enable-coupon="true" id="coupon_checkbox_trigger" />
                <label for="coupon_checkbox_trigger">Have a Promo Code?</label>
              </div>
              <br />
              <div class="grey-box onestepcheckout-coupons" data-coupon-block="true" style="display:none;">
                <h4 for="id_couponcode"><?php echo $this->__('Coupon code:'); ?></h4>
                <div class="inline-inputs">
                  <div class="inline-input-field"><input class="input-text white" type="text" name="onestepcheckout-couponcode" id="id_couponcode" value="<?php echo Mage::helper('core')->escapeHtml($_couponcode); ?>" /></div>
                  <button id="onestepcheckout-coupon-add" class="btn btn-black form-button-alt" type="btn btn-black"><?php echo $this->__('Apply Coupon'); ?></button>
                </div>
                <script type="text/javascript">
                  ;(function($, $j, window, undefined)
                  {

                    $j(document).on('click','[data-enable-coupon]', function(e)
                    {
                      $j('[data-coupon-block]').show();
                      $j(this).parent().hide();
                    })

                    // ADD COUPON
                    $('onestepcheckout-coupon-add').observe('click', function(e)
                    {
                      e.stop();

                      var coupon = $('id_couponcode').getValue(),
                          couponNotice = $('coupon-notice');

                      if(coupon == '')
                      {
                        alert('<?php echo $this->__('Please enter a valid coupon code.'); ?>');
                        return;
                      }

                      var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_coupon', array('_secure' => true ) ); ?>',
                          parameters = {code: coupon},
                          shipping_methods = $$('.shipment-methods').first(),
                          payment_methods = $$('.payment-methods').first(),
                          summary = $$('.onestepcheckout-summary').first();

                      if(shipping_methods)
                      {
                        shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
                      }

                      if(payment_methods)
                      {
                        payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
                      }

                      summary.update('<div class="loading-ajax">&nbsp;</div>');

                      new Ajax.Request(url, {
                          method: 'post',
                          parameters: parameters,
                          onSuccess: function(transport)
                          {
                            if(transport.status == 200)
                            {
                                var response = transport.responseText.evalJSON(),
                                    url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true )); ?>',
                                    update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                                // UPDATE SHIPPING BLOCK
                                if(shipping_methods)
                                {
                                  shipping_methods.hide();
                                  shipping_methods.update(response.shipping_method);
                                  shipping_methods.show();
                                  $$('.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
                                  $$('.shipment-methods input').invoke('observe', 'click', function()
                                  {
                                    $$('.onestepcheckout-shipment-method-error').each(function(item)
                                    {
                                      $j(this).fadeIn();
                                    });
                                  });
                                }

                                // UPDATE BILLING BLOCK
                                if(payment_methods)
                                {
                                  payment_methods.hide();
                                  payment_methods.replace(response.payment_method);
                                  payment_methods.show();

                                  paymentContainer = $('container_payment_method_' + payment.currentMethod)
                                  paymentForm = $('payment_form_' + payment.currentMethod)

                                  if(paymentContainer != null)
                                  {
                                    paymentContainer.show();
                                  }

                                  if(paymentForm != null)
                                  {
                                    paymentForm.show();
                                  }

                                  $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                                  $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function()
                                  {
                                    $$('.onestepcheckout-payment-method-error').each(function(item)
                                    {
                                      new Effect.Fade(item);
                                    });
                                  });
                                }

                                // UPDATE SUMMARY BLOCK
                                summary.hide();
                                summary.update(response.summary);
                                summary.show();

                                couponNotice.update('<p>' + response.message + '</p>');

                                if(response.success)
                                {
                                  couponNotice.removeClassName('error-msg');
                                  couponNotice.addClassName('success-msg');
                                }
                                else
                                {
                                  couponNotice.removeClassName('success-msg');
                                  couponNotice.addClassName('error-msg');
                                  //$('onestepcheckout-coupon-remove').hide();
                                }

                                couponNotice.show();
                            }
                          }
                      });
                    });

                  })($, jQuery, window);
                </script>
              </div>
              <div id="coupon-notice" data-checkout-alert="true" style="display: none;"></div>

            <?php endif; ?>


            <!-- GIFTCARDS -->
            <?php /* if($this->settings['enable_giftcard']): $_hasGiftCards = unserialize($this->getQuote()->getGiftCards()); $_giftcardcode = $this->getQuote()->getgiftcardCode(); ?>
            <div class="grey-box onestepcheckout-giftcards">
              <?php echo $this->getChildHtml('ugiftcert'); ?>

              <div id="giftcard-notice" style="display: none;"></div>
              <h4 for="id_giftcardcode"><?php echo $this->__('giftcard code:'); ?></h4><br/>
              <div class="inline-inputs">
                <div class="inline-input-field"><input class="input-text white" type="text" name="onestepcheckout-giftcardcode" id="id_giftcardcode" value="<?php echo Mage::helper('core')->escapeHtml($_giftcardcode); ?>" /></div>
                <button id="onestepcheckout-giftcard-add" class="btn btn-black form-button-alt" type="button" style="<?php if(!empty($_hasGiftCards)) { echo 'display: none;'; } ?>"><?php echo $this->__('Apply giftcard'); ?></button>
                <button id="onestepcheckout-giftcard-remove" class="btn btn-black form-button-alt" type="button" style="<?php if(empty($_hasGiftCards)) { echo 'display: none;'; } ?>"><?php echo $this->__('Cancel giftcard'); ?></button>
              </div>
              <script type="text/javascript">
                document.observe('dom:loaded', function()
                {
                  $('onestepcheckout-giftcard-add').observe('click', function(e)
                  {
                    e.stop();
                    var giftcard = $('id_giftcardcode').getValue();
                    var giftcardNotice = $('giftcard-notice');
                    giftcardNotice.hide();

                    if(giftcard == '')
                    {
                      alert('<?php echo $this->__('Please enter a valid giftcard code.'); ?>');
                      return;
                    }

                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_giftcard', array('_secure'=>true)); ?>';
                    var parameters = {code: giftcard};
                    var shipping_methods = $$('.shipment-methods').first();
                    var payment_methods = $$('.payment-methods').first();
                    var summary = $$('.onestepcheckout-summary').first();

                    if(shipping_methods)
                    {
                        shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    if(payment_methods)
                    {
                        payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url+Math.random(1000), {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport)
                        {
                            if(transport.status == 200)
                            {
                                var response = transport.responseText.evalJSON();

                                var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
                                var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                                if(shipping_methods)
                                {
                                  shipping_methods.hide();
                                  shipping_methods.update(response.shipping_method);
                                  shipping_methods.show();
                                  $$('.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));

                                  $$('.shipment-methods input').invoke('observe', 'click', function()
                                  {
                                    $$('.onestepcheckout-shipment-method-error').each(function(item)
                                    {
                                      new Effect.Fade(item);
                                    });
                                  });
                                }

                                if(payment_methods)
                                {
                                  payment_methods.replace(response.payment_method);

                                  paymentContainer = $('container_payment_method_' + payment.currentMethod)
                                paymentForm = $('payment_form_' + payment.currentMethod)

                                  if(paymentContainer != null)
                                  {
                                    paymentContainer.show();
                                  }

                                  if(paymentForm != null)
                                  {
                                    paymentForm.show();
                                  }
                                  $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                                  $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function()
                                  {
                                      $$('.onestepcheckout-payment-method-error').each(function(item)
                                      {
                                          new Effect.Fade(item);
                                      });
                                  });
                                }

                                if(response.success)
                                {
                                  summary.update(response.summary);
                                  giftcardNotice.update(response.message);
                                  giftcardNotice.removeClassName('error-msg');
                                  giftcardNotice.addClassName('success-msg');
                                  giftcardNotice.show();
                                  $('onestepcheckout-giftcard-remove').show();
                                }
                                else
                                {
                                  summary.update(response.summary);
                                  giftcardNotice.update(response.message);
                                  giftcardNotice.removeClassName('success-msg');
                                  giftcardNotice.addClassName('error-msg');
                                  giftcardNotice.show();
                                  //$('onestepcheckout-giftcard-remove').hide();
                                }
                            }
                        }
                    });
                  });

                  $('onestepcheckout-giftcard-remove').observe('click', function(e)
                  {
                    var giftcard = $('id_giftcardcode').getValue();
                    var giftcardNotice = $('giftcard-notice');
                    giftcardNotice.hide();
                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_giftcard', array('_secure'=>true) ); ?>';
                    var parameters = {code: giftcard, remove: '1'};
                    var shipping_methods = $$('.shipment-methods').first();
                    var payment_methods = $$('.payment-methods').first();
                    var summary = $$('.onestepcheckout-summary').first();

                    if(shipping_methods)
                    {
                      shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    if(payment_methods)
                    {
                      payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url, {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport)
                        {
                          if(transport.status == 200)
                          {
                            var response = transport.responseText.evalJSON();

                            var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
                            var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                            if(shipping_methods)
                            {
                              shipping_methods.hide();
                              shipping_methods.update(response.shipping_method);
                              shipping_methods.show();
                              $$('.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
                              $$('.shipment-methods input').invoke('observe', 'click', function()
                              {
                                $$('.onestepcheckout-shipment-method-error').each(function(item)
                                {
                                  new Effect.Fade(item);
                                });
                              });
                            }

                            if(payment_methods)
                            {
                                $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                                $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function()
                                {
                                    $$('.onestepcheckout-payment-method-error').each(function(item)
                                    {
                                        new Effect.Fade(item);
                                    });
                                });

                                payment_methods.hide();
                                payment_methods.replace(response.payment_method);
                                payment_methods.show();

                                paymentContainer = $('container_payment_method_' + payment.currentMethod)
                                paymentForm = $('payment_form_' + payment.currentMethod)

                                if(paymentContainer != null)
                                {
                                    paymentContainer.show();
                                }

                                if(paymentForm != null)
                                {
                                    paymentForm.show();
                                }
                            }

                            if(response.success)
                            {
                              $('id_giftcardcode').setValue('')
                              $('onestepcheckout-giftcard-remove').hide();
                            }

                            var summary = $$('.onestepcheckout-summary').first();

                            summary.hide();
                            summary.update(response.summary);
                            summary.show();

                            giftcardNotice.hide();
                            giftcardNotice.update(response.message);
                            giftcardNotice.removeClassName('error-msg');
                            giftcardNotice.addClassName('success-msg');
                            giftcardNotice.show();
                          }
                        }
                    });
                  });
              });
              </script>
            </div>
            <?php endif; */ ?>

        </div>


        <?php // SHIPPING METHODS ?>
        <?php if(!$this->isVirtual()): $step_counter++; ?>

          <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_shipping_method')):?>
            <header class="checkout-step">
              <span class="checkout-step-number"><?php echo $step_counter; ?></span>
              <h2><?php echo $this->__('Shipping method'); ?></h2>
            </header>
            <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
              <div data-checkout-alert="true" class="error-msg">
                <p><?php echo $this->__('Please choose a shipping method.'); ?></p>
              </div>
            <?php endif; ?>
            <div class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">
              <?php echo $this->getChildHtml('choose-shipping-method'); ?>
            </div>
          <?php else: ?>
            <header class="checkout-step">
              <span class="checkout-step-number"><?php echo $step_counter; ?></span>
              <h2><?php echo $this->__('Shipping method'); ?></h2>
            </header>
            <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
              <div data-checkout-alert="true" class="error-msg">
                <p><?php echo $this->__('Please choose a shipping method.'); ?></p>
              </div>
            <?php endif; ?>
            <div class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">
              <div class="onestepcheckout-shipping-method-block">
                <?php echo $this->getChildHtml('choose-shipping-method'); ?>
              </div>
            </div>
          <?php endif; ?>

        <?php endif; ?>



        <?php $step_counter++; // PAYMENT METHODS ?>

          <header class="checkout-step">
            <span class="checkout-step-number"><?php echo $step_counter; ?></span>
            <h2><?php echo $this->__('Payment method'); ?></h2>
          </header>

          <div class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">
            <?php //var_dump( Mage::getStoreConfig('onestepcheckout/general/hide_payment_method') );?>
            <?php if( Mage::getStoreConfig('onestepcheckout/general/hide_payment_method') ):  ?>

              <?php if(!empty($this->formErrors['payment_method'])): ?>
                <div data-checkout-alert="true" class="error-msg">
                  <p><?php echo $this->__('Please choose a payment method.'); ?></p>
                </div>
              <?php endif; ?>

              <?php if(!empty($this->formErrors['payment_method_error'])): ?>
                <div data-checkout-alert="true" class="error-msg">
                  <p><?php echo $this->__('Please enter valid details below.'); ?></p>
                </div>
              <?php endif; ?>

            <?php else: ?>

              <?php if(isset($this->formErrors['payment_method']) && $this->formErrors['payment_method']): ?>
                <div data-checkout-alert="true" class="error-msg">
                  <p><?php echo $this->__('Please choose a payment method.'); ?></p>
                </div>
              <?php else: ?>

                <?php if(isset($this->formErrors['payment_method_error'])): ?>
                  <div data-checkout-alert="true" class="error-msg">
                    <p><?php echo $this->__('Please enter valid details below.'); ?></p>
                  </div>
                <?php endif; ?>

              <?php endif; ?>

            <?php endif; ?>

            <?php echo $this->getChildHtml('choose-payment-method'); ?>

          </div>


        <!-- COMMENTS -->
        <?php /* if($this->settings['enable_comments']): ?>
          <div class="onestepcheckout-comments">
            <label for="id_comments"><?php echo $this->__('Comments'); ?></label><br/>
            <textarea id="id_comments" name="onestepcheckout_comments"><?php if(isset($_POST['onestepcheckout_comments'])) { echo Mage::helper('core')->escapeHtml($_POST['onestepcheckout_comments']); } ?></textarea>
          </div>
        <?php endif; */ ?>



      </div>

    </div>



    <!-- SUMMARY -->
    <div class="wrapper">
      <?php $step_counter++;?>
      <header class="checkout-step">
        <span class="checkout-step-number"><?php echo $step_counter; ?></span>
        <h2><?php echo $this->__('Review your order'); ?></h2>
      </header>

      <div class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">
        <div class="onestepcheckout-summary">
          <?php echo $this->getChildHtml('summary'); ?>
        </div>
      </div>

      <?php $step_counter++;?>
      <header class="checkout-step">
        <span class="checkout-step-number"><?php echo $step_counter; ?></span>
        <h2><?php echo $this->__('Finish Checkout'); ?></h2>
      </header>

      <div class="checkout-step-body checkout-step-body-<?php echo $step_counter; ?>">

        <?php $terms_error = false;
          isset($this->formErrors['terms_error']) && $this->formErrors['terms_error'] ? $terms_error = true : '';
          $_SERVER['REQUEST_METHOD'] == 'POST' ? $terms_error = false : $terms_error = true ;

          if(isset($this->formErrors['terms_error']) && $this->formErrors['terms_error']): ?>
          <div class="onestepcheckout-error onestepcheckout-terms-error">
            <?php echo $this->__('You must accept our terms to continue.'); ?>
          </div>
        <?php endif; ?>

        <div class="wrapper table onestepcheckout-place-order-wrapper">
          <!-- NEWSLETTER SUBSCRIPTIONS -->
          <div class="table-cell two-third">
            <!-- DEFAULT TERMS -->
            <?php $agreements = Mage::getModel('checkout/agreement')->getCollection()->addStoreFilter( Mage::app()->getStore()->getId() )->addFieldToFilter('is_active', 1);
            if( count($agreements) && Mage::getStoreConfig('onestepcheckout/terms/enable_default_terms') ): ?>
              <div class="onestepcheckout-enable-terms checkbox">
                <input class="required-entry" type="checkbox" id="id_accept_terms" name="accept_terms" value="1" <?php if(!$terms_error) echo "checked=\"checked\""; ?> />
                <label for="id_accept_terms"><?php echo $this->__('I accept the <a data-popup-link="terms" href="#">Terms &amp; Conditions</a>'); ?></label>
              </div>
            <?php endif; ?>

          <?php $customerEmail = $this->isCustomerLoggedIn() ? $this->getQuote()->getCustomer()->getEmail() : false ;?>
          <?php if($this->settings['enable_newsletter'] && !$this->isSubScribed($customerEmail)): ?>
            <div class="checkbox onestepcheckout-enable-newsletter">
              <input type="checkbox" id="id_subscribe_newsletter" name="subscribe_newsletter" value="1" <?php if($this->settings['newsletter_default_checked']): ?>checked="checked"<?php endif; ?> />
              <label for="id_subscribe_newsletter"><?php echo $this->__('Subscribe to our newsletter'); ?></label>
            </div>
          <?php endif; ?>
        </div>

          <!-- CHECKOUT BUTTON -->
          <div class="table-cell third read-more">
            <div id="loading-process" style="display: none;"></div>
            <button type="button" id="onestepcheckout-place-order" class="btn btn-orange btn-big onestepcheckout-place-order" onclick="javascript:void(0);">
              <i class="fa fa-credit-card"></i>&nbsp;&nbsp;<?php echo $this->__('Place order'); ?>
            </button>
          </div>
        </div>
      </div>
    </div>

  </form>

  <!-- CCV Visual Reference -->
  <div data-popup="ccv" class="wrap table popup">
    <div class="table-cell popup-background">
      <div class="popup-body">
        <header data-header-mode="true" class="popup-header">
        <div class="table-cell">
          <h1 class="popup-title active"><?php echo $this->__('CCV Visual Reference'); ?></h1>
        </div>
        <div class="table-cell"><a href="#" id="popup-close-link" data-popup-close="true"><i class="fa fa-times"></i></a></div>
      </header>
        <div class="popup-body-inner">
        <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
      </div>
      </div>
    </div>
  </div>

  <?php if( count($agreements) > 0 && Mage::getStoreConfig('onestepcheckout/terms/enable_default_terms') ): //  ?>
  <div data-popup="terms" class="wrap table popup">
    <div class="table-cell popup-background">
      <div class="popup-body">
        <header data-header-mode="true" class="popup-header">
          <div class="table-cell">
            <h1 class="popup-title active"><?php echo $this->__('Terms & Conditions'); ?></h1>
          </div>
          <div class="table-cell"><a href="#" id="popup-close-link" data-popup-close="true"><i class="fa fa-times"></i></a></div>
        </header>
        <div class="popup-body-inner">
          <?php echo $this->getChildHtml('agreements'); ?>
        </div>
      </div>
    </div>
  </div>
  <?php endif; ?>

  <script type="text/javascript">
  var popup = popup_validate = '';

  ;(function($, window, undefined)
  {
    $j(document).ready(function()
    {
      popup = {
        el: '',
        mode: '',
        lock_body:function()
        {
          $(document.body).addClass('lock');
        },
        unlock_body:function()
        {
          $(document.body).removeClass('lock');
        },
        set_data: function( a )
        {
          if( a[0] != undefined )
          {
            this.el = a;
            this.mode = a.data('mode');
          }
        },
        show_popup:function()
        {
          this.el.addClass('active-popup');
          this.lock_body();
        },
        hide_popup:function()
        {
          this.el.removeClass('active-popup');
          this.unlock_body();
        }
      },
      popup_validate = {
        error_box:$('[data-popup-errors]'),
        error:{
          invalid_email:'<?php echo $this->__('Please enter a valid email address');?>',
          email_not_found: '<?php echo $this->__('Please enter a registered email address.');?>',
          no_email_password:'<?php echo $this->__('Enter your email below and well send you a new password by email.');?>',
          login_error:'<?php echo $this->__('Please login with your email address and password.');?>'
        },
        success:{
          forgot_success:'<?php echo $this->__('We have now sent you a new password to your email address. Click the link below to return to login.');?>',
        },
        clear_error_box:function()
        {
          this.error_box.fadeOut(200, function(){
            $j(this).html('');
          });
        },
        fill_box:function( msg, msg_class )
        {
          this.error_box.html('<p class="' + msg_class + '">' + msg + '</p>').fadeIn();
        }
      },
      popup_mode = {
        deactivate_forms:function( el )
        {
          el.find('form').each(function()
          {
            $j(this).removeClass('active-form');
          });

          popup_validate.clear_error_box();
        },
        activate_form:function( form_id )
        {
          $j('#'+form_id).addClass('active-form')
        },
        switch_title:function()
        {
          $j('[data-popup] [data-header-mode] h1').toggleClass('active')
        },
        switch_popup_mode:function( el )
        {
          popup.mode = el.data('switch-form-mode');
        },
        switch_forms:function( popup, el )
        {
          this.deactivate_forms(popup);
          this.switch_title();
          this.activate_form( el.data('switch-form-mode') )
        }
      }

      // FIRE POPUP
      $j(document).on('click', '[data-popup-link]', function(e)
      {
        e.preventDefault();
        var which = $j(this).data('popup-link'),
            el = $j('[data-popup='+ which +']');

        popup.set_data(el);
        popup.show_popup()
      })

      // CLOSE POPUP
      $j(document).on('click', '[data-popup-close]', function(e)
      {
        e.preventDefault();
        popup.hide_popup();
      })

      // SWITCH FORMS
      $j(document).on('click', '[data-switch-form-mode]', function(e)
      {
        e.preventDefault();
        popup_mode.switch_forms( popup.el, $j(this) );
        popup_mode.switch_popup_mode( $j(this) )
      })

      // FIRE AJAX CALLS TO SEND DATA TO CORRESPONDING ACTIONS
      $j('[data-login-form], [data-forgot-form]').submit(function(e)
      {
        e.preventDefault();

        var action = $j(this).data('action'),
            data = $j(this).serialize();

        popup_validate.clear_error_box();

        $j.ajax({
          url: action,
          method: 'POST',
          data: data,
          dataType: "json",
          success:function( data )
          {
            popup_validate.fill_box( data.error, data.success );

            if( popup.mode = 'login' && data.success )
            {
              setTimeout(function()
              {
                location.reload();
              },1000)
            }
          },
          error:function( data )
          {
            popup_validate.fill_box( data.error, data.success );
          }
        })

      });
    })

  })($j, window)

  </script>

  <?php // LOGIN FORM POPUP ?>
  <?php if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
    <?php echo $this->getChildHtml('LoginFormBox');  ?>
  <?php endif; ?>


  <?php if($helper->isValidateEmail()): ?>
  <script type="text/javascript">

  $('billing:email').observe('blur', function(e)
  {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true) ); ?>',
        email = e.element().getValue(),
        parameters = { email: email },
        loader = $j('[data-email-checking]');

    loader.show();

    new Ajax.Request(url, {
      parameters: parameters,
      onComplete: function(response)
      {
        if(response.status == 200)
        {
          var result = response.responseText.evalJSON().result;

          loader.hide();

          if(result == 'invalid')
          {
            $('onestepcheckout-email-error-message').update('<p><?php echo $this->__('Invalid email address.'); ?></p>');
            $('onestepcheckout-email-error').show();
          }
          else if(result == 'exists')
          {
            <?php if($this->settings['registration_order_without_password']): ?>
            // Remove the password fields if the email exists in database
            $('onestepcheckout-li-password').hide();
            <?php endif; ?>
            $('onestepcheckout-email-error-message').update('<?php echo $this->__('<p>Email address already registered. Please <a href="#" data-popup-link="login">login now</a> or use a different email address.</p>'); ?>');
            $('onestepcheckout-email-error').show();
            $('id_onestepcheckout_username').value = email;
          }
          else
          {
            $('onestepcheckout-email-error').hide();
            $('onestepcheckout-li-password').show();
          }
        }
      }
    })
  });

  Validation.add('validate-email', '<?php echo $this->__('This is a required field.') ?>', function(v)
  {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = v;
    var parameters = { email: email };
    var value = Validation.get('IsEmpty').test(v) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(v)

    new Ajax.Request(url, {
      parameters: parameters,
      asynchronous: false,
      onComplete: function(response)
      {
        if(response.status == 200)
        {
          var result = response.responseText.evalJSON().result;

          if(result == 'invalid')
          {
            value = false;
          }
          else if(result == 'exists')
          {
            <?php if($this->settings['registration_order_without_password']): ?>
            $('onestepcheckout-li-password').hide();
            <?php endif; ?>
            $('onestepcheckout-email-error-message').update('<?php echo $this->__('<p>Email address already registered. Please <a href="javascript:void(0);" onclick="popup.show_popup(); return false;">login now</a> or use a different email address.</p>'); ?>');
            $('onestepcheckout-email-error').show();
            $('id_onestepcheckout_username').value = email;
            value =  false;
          }
        }
      }
    })
    return value;
  });

  </script>
  <?php endif; ?>

  <?php if($this->hasFormErrors()): ?>
  <script type="text/javascript">
  if($$('.input-error').length > 0)
  {
    var input = $$('.input-error')[0].select('input');

    if(input.length == 1)
    {
      input[0].focus();
    }
  }
  </script>
  <?php endif; ?>

  <?php if(!$this->settings['exclude_region']): ?>
  <script type="text/javascript">
  //<![CDATA[
    countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

    <?php if($this->settings['enable_different_shipping'] && !$this->isVirtual()): ?>
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    <?php endif; ?>
  //]]>
  </script>
  <?php endif; ?>

  <script type="text/javascript">
  Event.observe(window, 'load', function()
  {
    if ($$('.shopping-cart-totals').length == 1)
    {

    }
    else
    {
        already_placing_order = false;
        review = false;
        reviewmodal = false;

        /* Handle place order click event */
        $$('.onestepcheckout-place-order').each(function(elem)
        {
            elem.observe('click', function(e)
            {
                Event.stop(e);

               // First validate the form
                var form = new VarienForm('onestepcheckout-form');

                if(!form.validator.validate())
                {
                  Event.stop(e);
                }
                else
                {
                    if(!already_placing_order && $$('.loading-ajax').length <= 0 )
                    {

                      <?php if(!empty($helper->settings['addressreview']['enable_addressreview'])):?>

                        var addressTemplates = {
                            shipping: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['shipping_template']));?>',
                            billing: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['billing_template']));?>'
                        };

                        addressPreview(addressTemplates, 'addressreview');

                        if(!review)
                        {
                            review = true;
                            if(!reviewmodal)
                            {
                                reviewmodal = new Control.Modal($('addressreview'),{
                                    overlayOpacity: 0.75,
                                    className: 'modal',
                                    fade: true,
                                    closeOnClick: false
                                });
                            }

                            reviewmodal.open();

                            reviewmodal.observe('beforeClose',function()
                            {
                              review = false;
                            });

                            return true;
                            Event.stop(e);

                        }
                        else
                        {
                            reviewmodal.close();
                        }

                      <?php endif;?>

                        already_placing_order = true;

                        var submitelement = $('onestepcheckout-place-order');

                        var loaderelement = new Element('div').
                            addClassName('onestepcheckout-place-order-loading').
                            update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" />&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...'); ?>');

                        submitelement.parentNode.appendChild(loaderelement);

                        /* Disable button to avoid multiple clicks */
                        submitelement.removeClassName('orange').addClassName('grey');
                        submitelement.disabled = true;

                        /* Submit the form */
                        $('onestepcheckout-form').submit();
                    }
                }
            });
        });


        // This is a separate page
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

        $$('.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
        $$('.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', get_separate_save_methods_function(url));

        $$('.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', function()
        {
          $$('.onestepcheckout-payment-method-error').each(function(item)
          {
            new Effect.Fade(item);
          });
        });

        $$('.shipment-methods input').invoke('observe', 'click', function()
        {
          $$('div.onestepcheckout-shipment-method-error').each(function(item)
          {
            new Effect.Fade(item);
          });
        });

        var has_hidden_terms = false;

        if($('id_accept_terms') != null)
        {
          $('id_accept_terms').observe('click', function(e)
          {
            var element = e.element();

            if(element.checked)
            {
              $$('.onestepcheckout-terms-error').each(function(item)
              {
                new Effect.Fade(item);
                has_hidden_terms = true;
              });
            }
            else
            {
              if(has_hidden_terms)
              {
                $$('.onestepcheckout-terms-error').each(function(item)
                {
                  new Effect.Appear(item);
                  has_hidden_terms = false;
                });
              }
            }
          });
        }
    }

    var form = $('onestepcheckout-form');

    /* Highlight selected payment method if one set */
    if($RF(form, 'payment[method]') != null)
    {
      try
      {
        var payment_method = $RF(form, 'payment[method]');
        $('container_payment_method_' + payment_method).show();
        $('payment_form_' + payment_method).show();
      }
      catch(err)
      {

      }
    }

    /* Set default shipping method if not set */
    if($RF(form, 'shipping_method') == null)
    {
      try
      {
        var method = '<?php echo $this->_getDefaultShippingMethod(); ?>';

        if(method != '')
        {
          $('s_method_' + method).checked = true;
          get_separate_save_methods_function(url);
        }
      }
      catch(err)
      {

      }
    }

   //submit what's available on load
   get_separate_save_methods_function(url)();

  <?php if($this->differentShippingAvailable()): ?>

    $('billing:use_for_shipping_yes').observe('click', function(e)
    {
        var element = e.element();
        if(element.checked)
        {
          $('shipping_address').hide();
        }
        else
        {
          if($('shipping-address-select') && $('shipping-address-select').value == '')
          {
            $('shipping_address_list').show()
          }

          $('shipping_address').show();

          <?php if(!$this->isCustomerLoggedIn()):?>
            $('shipping_address_list').show()
          <?php endif;?>

          <?php if($this->isCustomerLoggedIn()):?>
            if(!$('shipping-address-select') && $('shipping_address_list').getStyle('display')=='none')
            {
                $('shipping_address_list').show()
            }
          <?php endif;?>
        }

        <?php if($this->settings['enable_ajax_save_billing']): ?>
        get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>', <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>, true)();
        <?php endif; ?>

    });
    <?php endif; ?>

    <?php $triggers = Mage::getStoreConfig('onestepcheckout/ajax_update/ajax_save_billing_fields');

      if(!empty($triggers))
      {
        $triggers = str_replace('country', 'country_id', $triggers);
        $triggers = str_replace('state/region', 'region_id', $triggers);
        $triggers = explode(',',$triggers);

        if(in_array('region_id',$triggers))
        {
          $triggers[] = 'region';
        }
      }
    ?>

    <?php if(Mage::getStoreConfig('onestepcheckout/ajax_update/enable_ajax_save_billing') && !empty($triggers)):?>

        var url_save_billing = '<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>';
        var url_set_methods = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;
        var update_on_initial = false;

        var euvat = $('euvat_action_validate_taxvat');

        if(euvat !== null)
        {
          euvat.observe('click', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
        }

        var euvatid = $('billing:vat_id');

        if(euvatid !== null)
        {
          euvatid.observe('click', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
        }

        triggers = ['<?php echo implode ('\',\'',$triggers)?>'];
        btriggered = [];
        striggered = [];

        <?php
        foreach($triggers as $value)
        {
            echo (($this->getQuote()->getBillingAddress()->getData($value)) ? 'btriggered.push(\'billing:'.$value.'\');' : '');
            echo (($this->getQuote()->getShippingAddress()->getData($value)) ? 'striggered.push(\'shipping:'.$value.'\');' : '');
        } ?>


        bcountry_id = $('billing:country_id');
        if(bcountry_id)
        {
          if(bcountry_id.getValue())
          {
            if(!btriggered.include('billing:country_id'))
            {
              btriggered.push('billing:country_id');
            }
          }
        }

        scountry_id = $('shipping:country_id');
        if(scountry_id)
        {
          if(scountry_id.getValue())
          {
            if(!striggered.include('shipping:country_id'))
            {
              striggered.push('shipping:country_id');
            }
          }
        }

        batriggered = false;
        satriggered = false;

        changeTimer = false;
        changeInterval = 1000;

        triggers.each(function(item)
        {
            var belement = $('billing:'+item);
            if(belement)
            {
              belement.observe('change', function(e)
              {
                var element = e.element();
                var id = element.id;
                var tagname = element.tagName;
                if(tagname === 'SELECT')
                {
                  clearTimeout(changeTimer);
                  changeTimer = setTimeout(bcallbackEvent, changeInterval, id);
                }
                else
                {
                  bcallbackEvent(id);
                }
              });
            }

            var selement = $('shipping:'+item);
            if(selement)
            {
              selement.observe('change', function(e)
              {
                var element = e.element();
                var id = element.id;
                var tagname = element.tagName;
                if(tagname === 'SELECT')
                {
                  clearTimeout(changeTimer);
                  changeTimer = setTimeout(scallbackEvent, changeInterval, id);
                }
                else
                {
                  scallbackEvent(id);
                }
              });
            }
        });

        function scallbackEvent (id)
        {
          if(!striggered.include(id))
          {
            striggered.push(id);
          }
          if(striggered.length >= triggers.length-1)
          {
            satriggered = true;
          }

          get_save_billing_function(url_save_billing, url_set_methods, update_payments, satriggered)();
        }


        function bcallbackEvent (id)
        {
          if(!btriggered.include(id))
          {
              btriggered.push(id);
          }

          if(btriggered.length >= triggers.length-1)
          {
              batriggered = true;
          }
          get_save_billing_function(url_save_billing, url_set_methods, update_payments, batriggered)();
        }


        <?php if($this->isCustomerLoggedIn()):?>
          var bselect = $('billing-address-select');
          var sselect = $('shipping-address-select');
          if(bselect)
          {
            bselect.observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
          }

          if(sselect)
          {
            sselect.observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments, true));
          }
        <?php endif;?>

    <?php endif; ?>

  });
  </script>

<?php endif; ?>

</div>

<!-- DEFAULT TERMS POPUP -->
<?php /*if($this->settings['enable_terms']): ?>
<div id="onestepcheckout-toc-popup" style="display: none;">
  <div class="onestepcheckout-popup-wrapper">
    <div class="onestepcheckout-popup-wrapper-inner">
      <h1><?php echo $this->settings['terms_title']; ?></h1>
      <div class="onestepcheckout-toc-terms">
        <?php echo $this->settings['terms_contents']; ?>
      </div>
      <p class="close">
        <a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a>
      </p>
    </div>
  </div>
</div>
<script type="text/javascript">
Event.observe(window, 'load', function()
{
      var termsPopup = new Control.Modal($('onestepcheckout-toc-popup'), {
          overlayOpacity: 0.65,
          fade: true,
          fadeDuration: 0.3
      });

      $('onestepcheckout-toc-link').observe('click', function(e)
      {
        e.preventDefault();
        termsPopup.open();
      });

      $$('div#onestepcheckout-toc-popup p.close a').invoke('observe', 'click', function(e)
      {
        e.preventDefault();
        termsPopup.close();
      });
});


var popup;
Event.observe(window, 'load', function()
{
  popup = new OneStepCheckout_Popup('onestepcheckout-toc-popup','onestepcheckout-toc-link', 'div#onestepcheckout-toc-popup p.close a');

});

</script>


<button id="onestepcheckout-coupon-remove" class="btn btn-black form-button-alt" type="btn btn-black" style="<?php if($_couponcode == '') { echo 'display: none;'; } ?>"><?php echo $this->__('Cancel Coupon'); ?></button>
<script>

// REMOVE COUPON
$('onestepcheckout-coupon-remove').observe('click', function(e)
{
  e.stop();
  var coupon = $('id_couponcode').getValue();
  var couponNotice = $('coupon-notice');

  var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_coupon', array('_secure' => true) ); ?>',
      parameters = {code: coupon, remove: '1'},
      shipping_methods = $$('.shipment-methods').first(),
      payment_methods = $$('.payment-methods').first(),
      summary = $$('.onestepcheckout-summary').first();

  if( shipping_methods ) { shipping_methods.update('<div class="loading-ajax">&nbsp;</div>'); }
  if( payment_methods )  { payment_methods.update('<div class="loading-ajax">&nbsp;</div>');  }
  summary.update('<div class="loading-ajax">&nbsp;</div>');

  new Ajax.Request(url, {
      method: 'post',
      parameters: parameters,
      onSuccess: function(transport)
      {
        if(transport.status == 200)
        {
          var response = transport.responseText.evalJSON();

          if(response.success)
          {
            $('id_couponcode').setValue('')
            $('onestepcheckout-coupon-remove').hide();
          }

          var url = '<?php echo $this->getUrl( 'onestepcheckout/ajax/set_methods_separate', array('_secure'=>true) ); ?>';
          var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

          if(shipping_methods)
          {
            shipping_methods.hide();
            shipping_methods.update(response.shipping_method);
            shipping_methods.show();

            $$('.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
            $$('.shipment-methods input').invoke('observe', 'click', function()
            {
              $$('.onestepcheckout-shipment-method-error').each(function(item)
              {
                new Effect.Fade(item);
              });
            });
          }

          if(payment_methods)
          {
            payment_methods.hide();
            payment_methods.replace(response.payment_method);
            payment_methods.show();

            paymentContainer = $('container_payment_method_' + payment.currentMethod)
            paymentForm = $('payment_form_' + payment.currentMethod)

            if(paymentContainer != null)
            {
              paymentContainer.show();
            }

            if(paymentForm != null)
            {
              paymentForm.show();
            }

            $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
            $$('.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function()
            {
              $$('.onestepcheckout-payment-method-error').each(function(item)
              {
                new Effect.Fade(item);
              });
            });
          }

          summary.hide();
          summary.update(response.summary);
          summary.show();

          couponNotice.hide();
          couponNotice.update(response.message);
          couponNotice.removeClassName('error-msg');
          couponNotice.addClassName('success-msg');
          couponNotice.show();

          $('onestepcheckout-coupon-add').show();
        }
      }
  });
});



</script>


<?php endif;


<!-- GIFT MESSAGES -->
        <?php /* if($this->settings['enable_gift_messages']): ?>
          <div id="onestepcheckout-giftmessages">
            <div class="onestepcheckout-giftmessagecontainer">
              <?php echo $this->helper('onestepcheckout/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
            </div>
          </div>
        <?php endif;*/ ?>


        <!-- EXTRA PRODUCTS??? -->
        <?php /* $_extraProductsHelper = Mage::helper('onestepcheckout/extraproducts'); ?>
          <?php if($_extraProductsHelper->hasExtraProducts()): ?>
          <div class="onestepcheckout-extraproducts">
            <ul>
            <?php foreach($_extraProductsHelper->getExtraProducts() as $product): ?>
              <li><input type="checkbox" class="onestepcheckout-extra-product"
              <?php if($_extraProductsHelper->productInCart($product->getId())): ?>
                  checked="checked" <?php endif; ?>
                  name="extra_products_<?php echo $product->getId(); ?>"
                  id="id_extra_product_<?php echo $product->getId(); ?>" /> &nbsp;
              <label for="id_extra_product_<?php echo $product->getId(); ?>"> <?php echo $product->getName(); ?>
              <span><?php echo Mage::helper('checkout')->formatPrice($product->getPrice()); ?></span>
              </label></li>
              <?php endforeach; ?>
            </ul>
          </div>
          <script type="text/javascript">
            Event.observe(window, 'load', function()
            {
                $$('input.onestepcheckout-extra-product').invoke('observe', 'click', function(e)
                {
                    var id_temp = e.element().id.split('id_extra_product_');
                    if(id_temp.length == 2)
                    {
                        var product_id = id_temp[1];
                        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_extra_product'); ?>';
                        var parameters = {
                            product_id: product_id
                        }

                        if(!e.element().checked)
                        {
                          parameters['remove'] = 1;
                        }

                        var summary = $$('div.onestepcheckout-summary').first();
                        summary.update('<div class="loading-ajax">&nbsp;</div>');

                        new Ajax.Request(url, {
                            method: 'post',
                            parameters: parameters,
                            onSuccess: function(transport)
                            {
                              summary.update(transport.responseText);
                            }
                        });
                   };
                });
            });
        </script>
        <?php endif; */ ?>


        <!-- FEEDBACK -->
        <?php /* if(!empty($this->settings['feedback']['enable_feedback']) && !empty($this->settings['feedback']['feedback_values'])):?>
          <?php $selectedFeedBackFields = $this->getRequest()->getPost('onestepcheckout-feedback', false); $feedbackValues = unserialize($this->settings['feedback']['feedback_values']); ?>
          <div class="onestepcheckout-feedback" id="">
            <label for="id_feedback"><?php echo $this->__('How did you hear about us?'); ?></label><br>
            <select style="" name="onestepcheckout-feedback" id="id_feedback" defaultvalue="">
              <option value=""><?php echo $this->__('Please choose'); ?></option>
              <?php foreach($feedbackValues as $value => $label):
                  $selected= (!empty($selectedFeedBackFields) && $selectedFeedBackFields == $value) ? ' selected' : '';
              ?>
              <option value="<?php echo $value?>" <?php echo $selected;?>><?php echo $label['value']?></option>
              <?php endforeach;?>
              <?php if(!empty($this->settings['feedback']['enable_feedback_freetext'])):
                  $selected= (empty($feedbackValues[$selectedFeedBackFields]) && $selectedFeedBackFields != '') ? ' selected' : '';
              ?>
              <option value="freetext" <?php echo $selected;?>><?php echo $this->__('Other'); ?></option>
              <?php endif;?>
            </select>
          </div>
          <?php if(!empty($this->settings['feedback']['enable_feedback_freetext'])):?>
            <script type="text/javascript">
              $('id_feedback').observe('change', function (event)
              {
                if(this.getValue() == 'freetext')
                {
                  $('id_feedback_freetext_div').show();
                }
                else
                {
                  $('id_feedback_freetext_div').hide();
                }
              });
            </script>
            <div id='id_feedback_freetext_div' class="onestepcheckout-feedback-freetext"<?php echo ((!empty($selectedFeedBackFields) && $selectedFeedBackFields == 'freetext') ? '' : ' style="display: none;"'); ?>>
              <label for="id_feedback_freetext"><?php echo $this->__('Please specify:'); ?></label><br/>
              <textarea id="id_feedback_freetext" name="onestepcheckout-feedback-freetext"><?php echo Mage::helper('core')->escapeHtml($this->getRequest()->getPost('onestepcheckout-feedback-freetext', false));?></textarea>
            </div>
          <?php endif; ?>
        <?php endif; */ ?>




          <!-- DEFAULT TERMS -->
          <?php /* if($this->settings['enable_default_terms']): ?>
            <?php if(!empty($this->formErrors['agreements_error'])):?>
              <div class="onestepcheckout-error onestepcheckout-terms-error">
                <?php echo $this->__('Please agree to all the terms and conditions before placing the order.'); ?>
              </div>
            <?php endif; echo $this->getChildHtml('agreements') ?>
            <script type="text/javascript">

              var termsmodals = new Object;

              document.observe('dom:loaded', function()
              {
                $$('.checkout-agreements li p input').each(function(elem)
                {
                  elem.addClassName('required-entry');
                });
              });

              <?php if($this->settings['enable_textarea']):?>
              document.observe('dom:loaded', function()
              {
                $$('.checkout-agreements li p label').each(function(elem)
                {
                  elem.up().insert('<a href="javascript:void(0);" onclick="termsmodals[\'' + elem.htmlFor + '\'].open();">' + elem.innerHTML + '</a>');
                  elem.hide();
                });

                $$('div.agreement-content').each(function(element)
                {
                  element.id = 'agreement-div-' + element.up('li').down('input').id;
                  $$('body')[0].insert(element);
                });

                $$('.checkout-agreements li p input').each(function(elem)
                {
                  window.termsmodals[elem.id] = new Control.Modal($('agreement-div-' + elem.id),{
                      overlayOpacity: 0.75,
                      className: 'modal',
                      fade: true,
                      closeOnClick: true,
                      height: 400,
                      width: 700
                  });
                });
              });
              <?php endif;?>

            </script>
          <?php endif; */ ?>



