<?php $_coreHelper = $this->helper('core'); $checkoutHelper = Mage::helper('onestepcheckout/checkout'); ?>

<div class="wrapper checkout-summary">

<div class="col two-third">

  <table class="data-table checkout-review">

    <thead>
      <th class="checkout-name"><?php echo $this->__('Product'); ?></th>
      <th class="checkout-image">&nbsp;</th>
      <th class="checkout-qty"><?php echo $this->__('Qty'); ?></th>
      <th class="checkout-total"><?php echo $this->__('Subtotal'); ?></th>
    </thead>

    <?php foreach( $this->getItems() as $item ):

        $checkout_product = $item->getProduct();

        if( $checkout_product->isConfigurable() )
        {
          $ChildProduct = Mage::getModel('catalog/product')->loadByAttribute('sku', $checkout_product->getSku() );
          $url          = Mage::helper('catalog/image')->init($ChildProduct, 'thumbnail')->resize(80,80);
        }
        else
        {
          $url          = Mage::helper('catalog/image')->init($checkout_product, 'small_image')->resize(80,80);
        }
    ?>
      <tr>

        <td class="checkout-image">
          <img src="<?php echo $url ?>" alt="<?php echo $this->escapeHtml($checkout_product->getProductName()) ?>" />
        </td>

        <td class="checkout-name">
          <p><?php echo $item->getName(); ?></p>
          <?php if($checkoutHelper->settings['show_custom_options']):

            $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());

            if(isset($options['options']) && count($options['options']) > 0): ?>
              <ul class="onestepcheckout-custom-options">
              <?php foreach($options['options'] as $option): ?>
                  <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
              <?php endforeach; ?>
              </ul>
            <?php endif;


            if($item->getProduct()->isConfigurable()):

              $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());

              if(is_array($configurable_options) && count($configurable_options) > 0): ?>

                <ul class="onestepcheckout-custom-options">
                  <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                  <?php endforeach; ?>
                </ul>

              <?php endif; ?>

            <?php endif; ?>


          <?php endif; ?>
        </td>

        <td class="checkout-qty">
          <p>
            <?php echo $item->getQty(); ?>
          </p>
        </td>

        <td class="checkout-total">
          <?php if($checkoutHelper->settings['display_tax_included']): ?>
            <p><?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?></p>
          <?php else: ?>
            <p><?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?></p>
          <?php endif; ?>
        </td>

      </tr>
    <?php endforeach; ?>

  </table>

</div>

<div class="col third">

  <table class="cart-totals checkout-totals onestep">
  <?php foreach( $this->getTotals() as $total ): ?>

    <?php if( !$total->getTitle() ){ continue; }

      $fullInfo = $total->getFullInfo();

        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):

          foreach ($fullInfo as $info):
            $rates = current($info['rates']);
            $amount = $info['amount']; ?>

            <tr>
              <td class="title">
                <?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)
              </td>
              <td class="value">
                <?php echo $this->helper('checkout')->formatPrice($amount); ?>
              </td>
            </tr>

        <?php endforeach;
        endif;?>

    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
        <td class="title">
            <?php $code = $total->getCode(); $value = $total->getValue();

            if($code == 'subtotal')
            {
              $total_name = $this->__('Subtotal');
            }
            elseif($code == 'shipping')
            {
              $total_name = $this->__('Shipping');

              if($checkoutHelper->settings['display_tax_included'])
              {
                  $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
              }
            }
            elseif($code == 'grand_total')
            {
              $total_name = $this->__('Grand total');
            }
            else
            {
              $total_name = $total->getTitle();
            } ?>

            <?php $total->getCode() == 'grand_total' ? print '<strong>'. $total_name .'</strong>' : print $total_name ;?>

        </td>

        <td class="value">
            <p><?php echo $this->helper('checkout')->formatPrice($value); ?></p>
        </td>
    </tr>

    <?php endforeach; ?>
</table>

</div>

<script type="text/javascript">
//<![CDATA[
  var total = <?php echo $this->getGrandTotal();?>;
  if(payment.reloadcallback)
  {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
    paymentrefresh(url);
    payment.countreload = 0;
    payment.reloadcallback = false;
  }
//]]>
</script>

</div>