<?php /* to override the default configurable options template  */

include_once 'attributeSwatches.php';

$_config      = $this->getJsonConfig();
$_json_config = addAttributeSwatches($_config);
$_product     = $this->getProduct();

if ($_product->isSaleable() && count($_json_config["attributes"])): ?>

<dl id="options-container-<?php echo $_product->getId(); ?>">
  <?php foreach ($_json_config["attributes"] as $_attribute): ?>

    <div class="configurable-label" id="label-attribute-<?php echo $_attribute["id"] ?>">
      <label class="required"><?php echo $_attribute["label"] ?> <span>*</span><span class="selected-label">&nbsp;</span></label>
    </div>

    <dd>
      <?php if (in_array($_attribute["swatch_type"], array("image", "child", "label"))) {  ?>
        <div id="attribute-<?php echo $_attribute["id"] ?>-container" class="product-swatches-container">
          <ul id="swatches-options-<?php echo $_attribute["id"] ?>" class="has-swatches" <?php /* if ($_attribute["swatch_type"] == "image") echo ' class="has-swatches"'*/ ?>>
            <?php $_gallery_images = array();

            $_load_swatch_from_gallery = Mage::getStoreConfig("attributeswatches/settings/images") == "gallery";

            if ($_attribute["swatch_type"] == "child" && $_load_swatch_from_gallery)
            {
              $_gallery = $_product->getSwatchesGalleryImages($_attribute["id"]);

              foreach ($_gallery as $_image)
              {
                $_gallery_images[$_image->getAttributeValue()] = $_image->getFile();
              }
            }

            foreach ($_attribute["options"] as $_option) { ?>

            <li>
              <?php

              switch ($_attribute["swatch_type"])
              {
                    case "child":

                      $_image = "";

                      if ($_load_swatch_from_gallery)
                      {
                        if(isset($_gallery_images[$_option["id"]]))
                        {
                          $_image = $this->helper('catalog/image')->init($_product, 'image', $_gallery_images[$_option["id"]]);
                        }
                        else
                        {
                          $_image = $this->helper('catalog/image')->init($_product, 'image');
                        }
                      }
                      else
                      {
                        $_image_product = Mage::getModel('catalog/product')->load($_option["products"][0]);
                        $_image = $this->helper('catalog/image')->init($_image_product, 'image');
                      } ?>

                      <a title="<?php echo $_option["label"] ?>"
                         data-original-title="<?php echo $_option["label"] ?>"
                         rel="<?php echo $_option["id"] ?>"
                         id="swatches_option_value_<?php echo $_option["id"] ?>"
                         href="<?php echo $_image; ?>"
                         rev="<?php echo $_image->resize(256); ?>">
                          <?php echo "<img src='" . $_image->resize(30) . "' title='" . $_option["label"] . "' alt='" . $_option["label"] . "'/>"; ?>
                      </a>

                      <span class="tooltip-container">
                        <span class="tooltip">
                          <span><?php echo $_option["label"] ?></span>
                        </span>
                      </span>

              <?php break;

                    case 'image': ?>

                        <a style="<?php echo $_option["swatch_value"] ?>"
                           data-original-title="<?php echo $_option["label"] ?>"
                           title="<?php echo $_option["label"] ?>"
                           rel="<?php echo $_option["id"] ?>"
                           id="swatches_option_value_<?php echo $_option["id"] ?>"
                           href="#" rev="">
                            <span><?php echo $_option["label"] ?></span>
                        </a>

                        <span class="tooltip-container">
                          <span class="tooltip">
                            <span><?php echo $_option["label"] ?></span>
                          </span>
                        </span>

              <?php break;

                    case 'label': ?>

                      <a class="" title="<?php echo $_option["label"] ?>" data-original-title="<?php echo $_option["label"] ?>"   rel="<?php echo $_option["id"] ?>" id="swatches_option_value_<?php echo $_option["id"] ?>" href="#">
                        <?php echo $_option["label"] ?>
                      </a>

              <?php break; } ?>

            </li>
        <?php }?>

          </ul>
        </div>
      <?php } ?>

      <select name="super_attribute[<?php echo $_attribute["id"] ?>]"
              id="attribute<?php echo $_attribute["id"] ?>"
              class="configurable-option-select required-entry super-attribute-select swatches-type-<?php echo $_attribute["swatch_type"]; ?>
              <?php echo (($_attribute["hideselect"]) ? "hideselect" : ""); ?>
              <?php echo (($_attribute["switchgallery"]) ? "switch-gallery" : ""); ?>">

          <option value=""><?php echo $this->__('Choose an Option...') ?></option>
      </select>

    </dd>
  <?php endforeach; ?>
  <div class="pinterest-button">
       <h4>Share on Pinterest!</h4>
        <br />
        <a href="//www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark"  data-pin-color="red" data-pin-height="28"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_red_28.png" style="width:auto;" /></a></span>
  </div>
</dl>

<script type="text/javascript">

function out_of_stock_string()
{
  return "<?php echo $this->__(" (Out of Stock)"); ?>";
}

var mng_Config = null;
var spConfig = null;

jQuery(document).ready(function()
{
  window.mng_Config = <?php echo Mage::helper('core')->jsonEncode($_json_config); ?>;
  window.mng_Config.containerId = 'options-container-<?php echo $_product->getId(); ?>';
  window.spConfig = new Product.Config(window.mng_Config);
  window.addNewConfigurableProductMethods();
  window.enableSwatchesOptions("first");
  window.swatchesSelectDefaultValueOnHash();
});


</script>
<?php endif; ?>
